llm_providers:
    - name: OpenAI
      type: openai-compatible
      api_key: ""
      endpoint: "https://api.openai.com/v1"
      models:
        - name: "gpt-3.5-turbo"
          max_tokens: 8192


tts_providers:
    - name: OpenAI
      type: openai-compatible
      api_key: ""
      endpoint: "https://api.openai.com/v1"
      models:
        - name: "gpt-3.5-turbo"
          max_tokens: 8192
          
embedding_providers:
    - name: OpenAI
      type: openai-compatible
      api_key: ""
      endpoint: "https://api.openai.com/v1"
      models:
        - name: "gpt-3.5-turbo"
          max_tokens: 8192